### ISSUE TITLE
Mendeley sorrows

### ISSUE THREAD

**Issue by arjenpdevries** [laura-dietz/tutorial-utilizing-kg#1]
The link should be:
https://www.mendeley.com/community/entity-linking-and-retrieval/

However, that still does not work perfectly; maybe need to be invited to the group before you can see the refs?

(And I need an account with Elsevier... why promote the publisher that does not provide IP&M as open access in the NL "big deals" between unis and publishers?! But that is another discussion :-))

**Comment by ejmeij** [comment]
Thanks, Arjen. I dumped Laura's big bibtex file in there and since then it's throwing an error: "Sorry, something went wrong. Please try again." And you should be able to see it without logging in even. Let me export the bibtex from there and dump it in the repo.
